### ISSUE TITLE
"Client is buggy (failed to deserialize query)."

### ISSUE THREAD

**Issue by fiLLLip** [bchavez/RethinkDb.Driver#11]
I tried to insert the following object
![image](https://cloud.githubusercontent.com/assets/1264369/11143165/7aaf9806-89f3-11e5-8fdd-5fa5389da904.png)
And here is the serialized version of the object I'm trying to insert, serialized with `JsonConvert.SerializedObject()`
![image](https://cloud.githubusercontent.com/assets/1264369/11143102/d93f7ac2-89f2-11e5-86ae-213e47805e72.png)

The error I get is `RethinkDb.Driver.ReqlClientError` `"Client is buggy (failed to deserialize query)."` with stacktrace
```
RethinkDb.Driver.Net.Connection.RunQuery[T](Query query)
RethinkDb.Driver.Net.Connection.run[T](ReqlAst term, Object globalOpts)
RethinkDb.Driver.Ast.ReqlAst.run[T](Connection conn, Object globalOpts)
RethinkDb.Driver.Ast.ReqlAst.run(Connection conn, Object globalOpts)
TestProject.DataAccess.Database.RethinkDb.UserService.Create(User obj) UserService.cs: line: 29
TestProject.Api.Controllers.DemoController.Get() DemoController.cs: line: 63
```

Is this a message from the server? Are we sending invalid data? What could be the issue here?

**Comment by bchavez** [comment]
Hi @fiLLLip ,

Yea, this is fixed in `master` via https://github.com/bchavez/RethinkDb.Driver/commit/c4fb1e0a6d397c7e3015bad77d17db1b19bbb19d 

Basically, when a cursor is used, we sent a `continue` without a query token. This should be fixed in next release. I'll leave the issue open we confirm it's fixed.

-Brian

**Comment by fiLLLip** [comment]
Great :+1:

**Comment by bchavez** [comment]
This should be fixed in **alpha6**. Please close the issue once you've confirmed all is well! Thanks! :+1: Again, thanks for all your help.

**Comment by fiLLLip** [comment]
It actually did not fix the issue. I have been researching a little more, and if i remove the content from the `TenantPermissions` array, I get a new error message:
```
MALFORMED PROTOBUF (missing field `type`)
```
The object I'm trying to insert looks like this:
```
            var user = new User()
            {
                Birthday = DateTimeOffset.UtcNow,
                DisplayName = "DemoUser",
                FirstName = "Demo",
                LastName = "User",
                Phone = "+4712345678",
                Email = "demo@example.com",
                TenantPermissions = new List<TenantPermission>()
                //{
                //    new TenantPermission()
                //    {
                //        TenantId = "d8cabad3-9890-4c58-85ed-8963ea908e90",
                //        DepartmentPermissions = new List<DepartmentPermission>()
                //        {
                //            new DepartmentPermission()
                //            {
                //                DepartmentId = Guid.NewGuid().ToString(),
                //                Permissions = new List<string>()
                //                {
                //                    MandarinCrm.Application.Authorization.Permissions.TenantAccess
                //                },
                //                Roles = new List<Role>()
                //                {
                //                    new Role()
                //                    {
                //                        Permissions = new List<string>()
                //                        {
                //                            MandarinCrm.Application.Authorization.Permissions.SuperAdmin
                //                        },
                //                        Name = "SuperUsers",
                //                        TenantId = "d8cabad3-9890-4c58-85ed-8963ea908e90"
                //                    }
                //                }
                //            }
                //        }
                //    }
                //}
            };
```
If I then change the object to the following, I get the same error message as reported.
```
            var user = new User()
            {
                Birthday = DateTimeOffset.UtcNow,
                DisplayName = "DemoUser",
                FirstName = "Demo",
                LastName = "User",
                Phone = "+4712345678",
                Email = "demo@example.com",
                TenantPermissions = new List<TenantPermission>()
                {
                    new TenantPermission()
                    {
                        TenantId = "d8cabad3-9890-4c58-85ed-8963ea908e90",
                        //DepartmentPermissions = new List<DepartmentPermission>()
                        //{
                        //    new DepartmentPermission()
                        //    {
                        //        DepartmentId = Guid.NewGuid().ToString(),
                        //        Permissions = new List<string>()
                        //        {
                        //            MandarinCrm.Application.Authorization.Permissions.TenantAccess
                        //        },
                        //        Roles = new List<Role>()
                        //        {
                        //            new Role()
                        //            {
                        //                Permissions = new List<string>()
                        //                {
                        //                    MandarinCrm.Application.Authorization.Permissions.SuperAdmin
                        //                },
                        //                Name = "SuperUsers",
                        //                TenantId = "d8cabad3-9890-4c58-85ed-8963ea908e90"
                        //            }
                        //        }
                        //    }
                        //}
                    }
                }
            };
```

If I skip to set a value to `TenantPermissions` (null), the object is created successfully with no errors. It seems like the trouble is when using arrays/lists

**Comment by bchavez** [comment]
Thanks @fiLLLip , looking into this. Sorry about the regression  in **alpha6**. I added more unit tests. Need a bit of time to figure this one out.

**Comment by fiLLLip** [comment]
Just tried the **alpha9**, and it works perfectly. No errors that I can spot. Empty arrays also works. Great work! :+1:
